### ISSUE TITLE
service.pp forces to use qpidd service

### ISSUE THREAD

**Issue by AblionGE** [Katello/puppet-pulp#100]
In service.pp it requires qpidd and it doesn't work if we use rabbitmq.

for example :
https://github.com/Katello/puppet-pulp/blob/e063ea463570c4cc878afc5069e2eba4e9703d11/manifests/service.pp#L13

**Comment by ehelms** [comment]
See https://github.com/Katello/puppet-pulp/pull/103 for a fix

**Comment by AblionGE** [comment]
thanks
