### ISSUE TITLE
Severe lack of answers file documentation

### ISSUE THREAD

**Issue by MTecknology** [Katello/puppet-pulp#105]
I'm unable to find a fully documented answers file with all available options documented. There are a few answers files that have some options and samples. However, there's nothing I've found that shows documents the options very well and no file that documents all available options.

This caused me some massive headaches deploying katello.

**Comment by stbenjam** [comment]
`katello-installer --help` shows every available option, a description, and the default value.

puppet-pulp isn't exposed at the top level, its used as a library by other classes.  If you want some particular options exposed at the top level you can file an issue on the bug tracker, more info at http://www.katello.org/community/index.html#support.
