### ISSUE TITLE
Wrong parameters in init

### ISSUE THREAD

**Issue by cristifalcas** [Katello/puppet-pulp#135]
init class has the following parameters:

  $messaging_event_notifications_enabled = $pulp::params::messaging_event_notifications_enabled,
  $messaging_event_notification_url = $pulp::params::messaging_event_notification_url,

In params class you define those 2:

  $messaging_event_notifications_enabled = false
  $messaging_event_notifications_url = undef

Notice that in init you use messaging_event_notification_url and in params  messaging_event_notification**_s_**_url

The correct way is to fix init or params?

**Comment by cristifalcas** [comment]
I see that the templates are using messaging_event_notification_url

**Comment by ehelms** [comment]
We should probably fix params so as not to have to bump the major version.

**Comment by ekohl** [comment]
Currently they match what has to be in server.conf.erb and they are defined in params.pp so I believe this has been fixed.
