### ISSUE TITLE
Pulp v2.8 does not work with SSL_CLIENT_S_DN_CN 

### ISSUE THREAD

**Issue by aeria** [Katello/puppet-pulp#138]
When using this pulp module by itself, after installation pulp-admin won't work for most commands.

/var/log/messages shows us:
`Mar 31 00:18:22 localhost pulp: pulp.server.webservices.middleware.exception:INFO: Authentication with username admin:admin:56fc5e8c5af5cd2789b2cdfc failed: preauthenticated remote user is missing.`

The apache log shows:
`logs/pulp-https_error_ssl.log:[Wed Mar 30 23:23:18.891305 2016] [ssl:warn] [pid 10862] [client 127.0.0.1:33780] AH02227: Failed to set r->user to 'SSL_CLIENT_S_DN_CN'
`

Removing this line made it all work again:
`conf.d/05-pulp-https.conf:SSLUsername SSL_CLIENT_S_DN_CN`

Someone with the same issue on a mailing list:
http://comments.gmane.org/gmane.linux.redhat.fedora.pulp/4099

**Comment by ehelms** [comment]
Hi Taz,

Can you give more info on your setup and configuration to help us reproduce?

**Comment by aeria** [comment]
Absolutely

`puppet module install katello-pulp`

  include ::apache
  include ::apache::mod::proxy
  include ::apache::mod::proxy_http
  include ::epel

And in my .pp file

`  class {'::pulp':
    enable_rpm    => true,
    enable_http   => true,
    manage_httpd  => true,
  }

  class {'::pulp::admin':
    enable_rpm => true,
    verify_ssl => false,
    require       => Class['::pulp'],
  }
`

I noticed this module doesn't have any acceptance tests yet. I'm looking at potentially writing some, but shying away as this Puppet module is not idempotent. Every run 'restarts' the workers daemon, which by its nature is never actually running but forks off.

**Comment by jlambert121** [comment]
I ran into the same issue this weekend with pulp 2.8.2, same fix.

**Comment by ehelms** [comment]
The inclusion of SSL_CLIENT_S_DN_CN is what allows for using certificate authorization to talk to Pulp vs using oauth. I think this might be more of a Pulp issue where it should be able to handle this situation . We could conditionally set this directive in the Apache configuration but I think ultimately Pulp should be able to handle it.

**Comment by jlambert121** [comment]
@ehelms I'm sorry, I'm not entirely following - probably due to my only partial understanding of how auth is done with pulp.  When you say it might be a pulp issue, can you elaborate?  Maybe this parameter should be there if you want to use cert auth and not if you use oauth?

**Comment by KrisBuytaert** [comment]
Same issue here .. trying to spin up a box with 2.8 .. one can log in .. but no commands work .. removing the SSL_CLIENT_S_DN_CN thingie fixes that.

**Comment by aeria** [comment]
Further to this, a fresh install of Katello 3.0 via the CentOS 7 instructions has the same error. Removing that same line, but this time in /etc/httpd/conf.d/katello.conf helps. When working around the fact nothing plays nice with SELinux, but that's another issue.

**Comment by timogoebel** [comment]
@ehelms : If I followed the discussion correctly, this still is not fixed for Katello. There is now just an option to overwrite the setting causing this issue that you cannot use pulp-admin. Do you think we should open an issue in Redmine to track this further?

**Comment by ekohl** [comment]
@timogoebel that sounds correct.

**Comment by ehelms** [comment]
From our research the way pulp and pulp-admin do certificates within the
Pulp auth code is incompatible with our use case and needs. I don't think
we can solve this on the Katello side. We either patch Pulp or wait for
Pulp 3.0 which will overhaul the auth system. If you want more details I
can go into them with links to the Pulp code.

**Comment by timogoebel** [comment]
@ehelms: Don't bother, thanks. That's fine. I just think, "pulp-admin" is the tool to debug pulp (at least for me) and it should work. That's all. ;-)
