### ISSUE TITLE
Update documentation with all settings available

### ISSUE THREAD

**Issue by rammaram06** [Katello/puppet-pulp#143]
Hi,

If possible, could you guys please update the documentation for this module with different settings it provides and how to use them? Something similar to old pulp-pulp module.

Thanks

**Comment by ehelms** [comment]
What is the old pulp-pulp module that you mention? And what sort of documentation are you wanting? All parameters are documented at the top of the manifests, e.g. https://github.com/Katello/puppet-pulp/blob/master/manifests/init.pp#L5

**Comment by ramreddy26** [comment]
Something like this? https://forge.puppet.com/pulp/pulp

**Comment by stbenjam** [comment]
Generally we don't put this in the README as it gets stale fast, the top of the .pp files documents the parameters.

For all the classes we intended users to use directly, we even have a test uses puppet lint to ensure every single param is documented.

**Comment by lmayorga1980** [comment]
Wondering if there is a parsing class documentation tags to make them part of the README.md.

**Comment by rgarrigue** [comment]
Hi

Just a :+1: about this topic, documentation is really lacking until you get the idea to have a look directly in the .pp

And if I'm not mistaken this module is the successor of pulp/pulp. You should update pulp/pulp README.md to link to this module, and set version to 9.999.999 (see the nginx modules in forge)

Best regards,

**Comment by ekohl** [comment]
Something like http://www.puppetmodule.info/modules/katello-pulp/puppet_classes/pulp then?

**Comment by rgarrigue** [comment]
Not really. I was thinking about something like
https://forge.puppet.com/puppet/nginx, a handfull of simple case examples
to display the possibilities, something that will be unlikely to deprecate
much. Then maybe a big complex example for the in-deep. Couple of comments
in between to get started. And a link in the end to you full reference
above :-)

2017-03-08 8:45 GMT+01:00 Ewoud Kohl van Wijngaarden <
notifications@github.com>:

**Comment by ekohl** [comment]
That makes total sense and it's feedback that I received at cfgmgmtcamp as well about theforeman modules. I'd be very interested in getting some examples of what users expect of it.

**Comment by ekohl** [comment]
With the updated docs and http://www.puppetmodule.info/modules/katello-pulp/puppet_classes/pulp, is this sufficiently addressed?

**Comment by rgarrigue** [comment]
@ekohl Seems very good. One suggestion though, add this puppetmodule.info link to the README.md (I serached quickly, maybe I missed it if it's here)

**Comment by ekohl** [comment]
@rgarrigue it's not and I will add it.
