### ISSUE TITLE
sh: repoquery: command not found

### ISSUE THREAD

**Issue by TJM** [Katello/puppet-pulp#154]
I am getting an error during each puppet run with the pulp module installed:

```
sh: repoquery: command not found
```

... which I am guessing is coming from `puppet-pulp/lib/facter/facts.rb`.

I think it should probably redirect stderr to /dev/null at the very least, if not check for the existence of the executable before trying to run it. 

Tommy

**Comment by walkamongus** [comment]
this is fixed in PR #115 -- just waiting for merge

**Comment by TJM** [comment]
Sorry, I did *try* to search, honest! ... the search in github is weak (or my github-search-fu is weak) :)

**Comment by stbenjam** [comment]
Sorry for the long time to review that PR @walkamongus, I had just one piece of feedback but it looks good to me otherwise.

Going to close this one, thanks @TJM!
