### ISSUE TITLE
EPEL and Pulp repos not deployed

### ISSUE THREAD

**Issue by ccnifo** [Katello/puppet-pulp#164]
pulp::install relies on yum to install pulp RPMs, but the repos.fedorapeople.org and EPEL repos mentioned in the Pulp doc are not deployed.
I suppose managing them in this module would be logical, ideally with a switch to make it optional. Do you agree? If yes, do you have any comments regarding how to implement it?

**Comment by riton** [comment]
BTW, current `pulp` main class design does not protect against resource containment and something like

```puppet
class { '::setup_my_repositories': } ->
class { '::pulp': }
```

leads to a _chicken and egg_ problem.
_pulp_ packages will try to install before any repository defined in the `setup_my_repositories` class get actually available.

Would you mind using _anchors_ / _contain_ ?
This would solve this problem as discussed [here](https://www.devco.net/archives/2012/12/13/simple-puppet-module-structure-redux.php#comment-175995) ?

**Comment by rgarrigue** [comment]
I got issues with repo and managed to get it working like this

```
Yumrepo <| |> ~> Exec['yum-cache'] -> Package <| |>

    # Solves conflict between compat-qpid-* et qpid-*
    yumrepo { 'epel':
      exclude => 'compat-qpid*',
    }
    # From https://repos.fedorapeople.org/repos/pulp/pulp/rhel-pulp.repo
    yumrepo { 'pulp-2-stable':
      baseurl             => 'https://repos.fedorapeople.org/repos/pulp/pulp/stable/2/$releasever/$basearch/',
      descr               => 'Pulp 2 Production Releases',
      enabled             => true,
      gpgcheck            => true,
      gpgkey              => 'https://repos.fedorapeople.org/repos/pulp/pulp/GPG-RPM-KEY-pulp-2',
      skip_if_unavailable => true,
    }
    ~>
    exec { 'yum-cache':
      command => '/usr/bin/yum clean all; /usr/bin/yum makecache',
    }
    ->
    class { '::pulp': ........ }
```

**Comment by ekohl** [comment]
In our installer we rely on other modules to do this. EPEL is already needed by our installer and otherwise puppet-foreman does this for us. The pulp repos are installed by katello-release. I'm not sure what the best solution here is.

**Comment by ekohl** [comment]
Yesterday I looked into this. The difficulty with this is that in the katello context we have our own repository while community members might prefer the pulp-2-stable repo you linked. Then there's also Fedora which already includes the packages itself. We could add a class for this where you can select the source, but it may become quite complex.

**Comment by rgarrigue** [comment]
That's what other are doing, especially if u wanna go for up-to-date packages, VS distro's shipped ones. Here's Nginx example from doc : 

```
class{'nginx':
    manage_repo => true,
    package_source => 'nginx-mainline'
}
```

**Comment by ekohl** [comment]
I agree it can be useful and I'll work on it, though I don't think we'll ever manage EPEL from this module.

**Comment by ekohl** [comment]
I submitted https://github.com/Katello/puppet-pulp/issues/229 as optional inclusions. I'm not sure if and how to expose this in init.pp. Maybe a ```manage_repo``` and ```repo_source``` argument or combined in one where an empty source means no source.

What do other people think of this?

**Comment by rgarrigue** [comment]
:+1:  for manage_repo and repo_source, but not combined: I wouldn't know how to ask for a managed repo with default value, which happen when I wrap the pulp class in a profiles::pulp

**Comment by ekohl** [comment]
I've submitted the related PR and I believe that's the best we can currently do. I'd rather not manage EPEL and I've also chosen not to include a repo_source parameter. Most users will expect upstream repositories and those in the Katello scenario will already have it enabled through other means.
