### ISSUE TITLE
show_diff on /etc/pulp/server.conf show passwords

### ISSUE THREAD

**Issue by ccnifo** [Katello/puppet-pulp#171]
During the first run or when applying a password change, _/etc/pulp/server.conf_ is modified and a diff is displayed showing the password, which may be logged. This may even lead the password to be exported and displayed in an external log analyzer. This applies to the default admin password, but more seriously to the MongoDB and message broker password.
The _/etc/pulp/server.conf_ resource should probably use the _show_diff = false_ parameter to avoid this potential leak.

**Comment by stbenjam** [comment]
That seams reasonable, if you want to open a PR we'll get it merged quickly, otherwise it'll be when one of the devs gets around to doing it.

**Comment by ccnifo** [comment]
I wrote some code providing the show_diff as a parameter. Given that's more like a security feature, I don't know if it's better to have it parametrized or to hardcode it?

**Comment by stbenjam** [comment]
That looks ok to me, I would also add it to any of the importers in manifests/config.pp as they also contain passwords.

**Comment by ccnifo** [comment]
4 files added, I'll open the PR, thanks.
