### ISSUE TITLE
OAuth enabled by default

### ISSUE THREAD

**Issue by ccnifo** [Katello/puppet-pulp#175]
The param _oauth_enabled_ defaults to true. OAuth has been [deprecated since Pulp 2.4 ](https://docs.pulpproject.org/user-guide/authentication.html#oauth), it might be set to false by default.

**Comment by ekohl** [comment]
Given the the insecure defaults (key/secret) we must do something and the next release will be a major release so I think we can change this. In the installer modules we can easily explicitly enable this and not break things.
