### ISSUE TITLE
Manage pulp repositories (pulp_repo provider)

### ISSUE THREAD

**Issue by joshuabaird** [Katello/puppet-pulp#179]
The module should be able to manage Pulp repositories.  The use-case here is that repositories (and sync schedules) are stored in Puppet and can be configured on multiple Pulp servers easily.  This will likely require a new pulp_repo provider.

Other thoughts:

* We should be able to define repos/schedules on 'master/parent' Pulp servers and then ensure these repositories are also defined on 'children' Pulp servers.  On the children Pulp servers, the sync should occur from the 'master/parent' server and not from the original repository source (RedHat, etc).

**Comment by SimonPe** [comment]
hey, i have some code for this (in our internal pulp profile) but it does need some cleanup, will look into cleaning it up or posting it somewhere so that other people can look at it.

types/providers i have (map ~ directly to the pulp api)
 - pulp_repo
 - pulp_importer
 - pulp_distributor
 - pulp_sync_schedule
 - pulp_user
 - pulp_permission

includes support for purging!

**Comment by joshuabaird** [comment]
This would be great!  Thanks, @SimonPe!

**Comment by ekohl** [comment]
So what's the status here? We do have some specialised pulp_repo providers (RPM, ISO, Puppet). They are implemented using pulp-admin and not the API. I recall @timogoebel also wanting direct API usage.

**Comment by SimonPe** [comment]
@ekohl sorry, I kind of lost track of this, I published my code at https://github.com/SimonPe/puppet-pulpapi as a kind of standalone module.
Ideally this would get integrated in this module, but as this is code we currently use internally, I wanted to avoid conflicting with anything in this module already.

I know there are still some minor bugs in there, and i might have fixed some of them in our intern repo already (i'd have to check).

I would have no problem if we look into cleaning it up in my repo before merging it here (or we could put it in a branch here, I don't really care). And I can certainly answer some questions on it. But i don't have a lot fo time to look at puppet code lately, so some help is wanted in getting it to production quality.

So if you care to take a look at the code and maybe create some issues on the repo if you have questions or see issues, I would be thankfull.

**Comment by cristifalcas** [comment]
I could try to move the code to runcible, but there are no rpms for this now. Only for foreman scl.

**Comment by cristifalcas** [comment]
I could try to move the code to runcible, but there are no rpms for this now. Only for foreman scl.

**Comment by ekohl** [comment]
Closing this in favor of https://github.com/Katello/puppet-pulp/issues/253
