### ISSUE TITLE
pulp-admin-client

### ISSUE THREAD

**Issue by rgarrigue** [Katello/puppet-pulp#201]
Hi again (sorry for the issue flooding btw)

I don't see any reason not to install the admin cli client ? Just adding it in `install.pp` would do

```
class pulp::install {
  package { ['pulp-server', 'pulp-selinux', 'python-pulp-streamer','pulp-admin-client']: ensure => $pulp::version, }
```

Best regards,

**Comment by ekohl** [comment]
The ```pulp::admin``` class should handle it for you.

**Comment by rgarrigue** [comment]
Oh... didn't saw that one. Back to what's said on another issues : this is lacking a mention in README.md, at least a couple of lines saying it does exist.

**Comment by ekohl** [comment]
I'll grant you README's are greatly lacking. Personally I think we need more examples of common uses.

**Comment by rgarrigue** [comment]
I'm gonna finish my own implementation, then give you the result for the
doc, as "one server full example".

2017-03-08 10:29 GMT+01:00 Ewoud Kohl van Wijngaarden <
notifications@github.com>:

**Comment by rgarrigue** [comment]
@ekohl while we are talking about features, is there something for static content repository (aka no ISO, no rpm, nothing, juste stuff I'm gonna drop manually here like somes tar.gz, .war, etc), or should I just add a apache::vhost ?

**Comment by ekohl** [comment]
I'm afraid I can't answer that because I don't know :)

**Comment by TJM** [comment]
@rgarrigue - It may not be exactly what you need, but we host the RPM-GPG-KEYS in /var/lib/pulp/static/rpm-gpg (which is available as https://pulpserver/pulp/static/rpm-gpg/)

**Comment by ekohl** [comment]
I'm going to close this issue. The admin feature should be better documented (https://github.com/Katello/puppet-pulp/pull/242) and easier to set up (https://github.com/Katello/puppet-pulp/pull/248) but the basis does exist.
