### ISSUE TITLE
Authentification issue

### ISSUE THREAD

**Issue by rgarrigue** [Katello/puppet-pulp#206]
Hi again, and sorry again for the flooding. The issue can be seen in other issue I submitted but I wanted to explain this point 

After pulp and pulp-admin installation task, I'm trying to get my repo & schedule set. Problem is, there's authentification issue.

Out of the box, it says `/root/.pulp/user-cert.pem` doesn't exist. Ok, so I added this

```
exec { 'pulp-auth':
      command => "/bin/pulp-admin login -u ${admin_login} -p ${admin_password}",
      creates => '/root/.pulp/user-cert.pem',
      require => [ Service['httpd'], File['/root/.pulp'] ],
    }
```

This is a bit of an issue but the workaround seems ok. Except that I end up with

```
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[epel-7]: Could not evaluate: https request for repo "epel-7# threw exception SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Connection details: url=https://test.vagrant.local:443/pulp/api/v2/repositories/epel-7///?details=True, cert_path=/root/.pulp/user-cert.pem.
```

We've been searching for clues around, down to pulp_rpmrepo's api.rb and around, switched on and off every ssl related option, destroy & recreated & provisionned the vagrant vm dozens of time, nothing. Maybe pulp_util.rb could be improved to avoid the /// but that's the only thing we ended up with. 

The thing is, the repos get created. Through `pulp-admin` I started a sync, and got my centos-7-updates mirror up and running. Although it's not idempotent as mentionned in #205 

Thanks again,

**Comment by TJM** [comment]
Just curious, if the "exec" above is the "recommended" approach to populating `/root/.pulp/user-cert.pem`? I did end up doing this manually, which is worse.

**Comment by walkamongus** [comment]
Since many of the provider's commands depend on the `pulp-admin` command, it seems like the provider should just not use any API calls, and require credentials to be set in the Puppet user's `~/.pulp/admin.conf` file (or parsed from another known, protected location). Then these issues go away, right?

**Comment by TJM** [comment]
Doesn't the pulp-admin command just use the API anyhow?

**Comment by walkamongus** [comment]
I think so. Unless there is something that has to be done by going directly to the API, just using `pulp-admin` seems easiest since authentication can be set without a lifetime.

**Comment by ekohl** [comment]
https://github.com/Katello/puppet-pulp/pull/248 should fix this.

> Doesn't the pulp-admin command just use the API anyhow?

It does.

**Comment by TJM** [comment]
I found an SSL authentication issue at the root of #245 too. That may be what was breaking you as well. Pulp-admin was working fine (with username and password), but SSL cert auth was failing. Set the following in heiradata or modify your "class" as appropriate:

```
pulp::ssl_username: false
```

That will remove the apache config line that breaks pulp-admin certs. ;)
