### ISSUE TITLE
katello/puppet-katello using yum_max_speed which is not in current puppet-pulp release

### ISSUE THREAD

**Issue by kallies** [Katello/puppet-pulp#207]
The puppet module katello/puppet-katello in version 6.0.3 is using the parameter yum_max_speed [1] for the pulp class. This parameter is not available in the current katello/puppet-pulp release (4.1.0). It is though available in the master branch.

[1] https://github.com/Katello/puppet-katello/blob/0cb19c23dc7b714de0c7961dd636093100faee1e/manifests/init.pp#L143

**Comment by ehelms** [comment]
Thanks @kallies - found this same issue working on 3.3.1 release of Katello. I will do a release of puppet-pulp.

**Comment by kallies** [comment]
Nice, thanks a lot @ehelms !

**Comment by ekohl** [comment]
4.2.0 and 4.3.0 have been released since. They should include the parameter.
