### ISSUE TITLE
How to use Pulp - need docs

### ISSUE THREAD

**Issue by djjudas21** [Katello/puppet-pulp#241]
I'm new to Pulp but I installed it with the Puppet module `katello/pulp` using this very basic manifest to begin with:

```puppet
class profile::pulp {
  include ::profile::apache
  include ::profile::apache::ssl
  include ::apache::mod::wsgi

  yumrepo { 'pulp-2-stable':
    descr               => 'Pulp 2 Production Releases',
    baseurl             => 'https://repos.fedorapeople.org/repos/pulp/pulp/stable/2/$releasever/$basearch/',
    enabled             => 1,
    skip_if_unavailable => 1,
    gpgcheck            => 1,
    gpgkey              => 'https://repos.fedorapeople.org/repos/pulp/pulp/GPG-RPM-KEY-pulp-2',
  }

  # katello/pulp
  class { '::pulp':
    enable_rpm    => true,
    enable_puppet => true,
    require       => Yumrepo['pulp-2-stable'],
  }
}
```

This runs cleanly on my CentOS 7 node, seems to install all the correct dependencies etc. I've followed the setup steps in the [Pulp docs](http://docs.pulpproject.org/en/2.13/user-guide/installation/f23-.html) and each step seems to be completed OK. However the Pulp application is non-functional. Navigating to `http://pulp.example.com` just prints out a directory listing, mostly `.wsgi` files which simply display the content if I click on them. Navigating to `https://pulp.example.com` gives Error 403 (Forbidden). There is nothing helpful in the Apache logs. I don't know much about Python/wsgi so I'm stuck.

So **either** the `katello/pulp` module is broken and doesn't install Pulp properly, **or** there is insufficient documentation to enable beginners to actually the module. Judging by the scores on [Puppet Forge](https://forge.puppet.com/katello/pulp/scores), almost everyone has rated the module as being too hard to use and having insufficient docs. I've read the comments in the manifests and they give a reasonable idea of what each individual parameter does, but the docs are desperately missing an overall guide of which components to install and how to do it.

For example, look at the now-deprecated [`pulp/pulp`](https://forge.puppet.com/pulp/pulp) module, which has explanatory notes and a complete worked example. Please would it be possible to add something similar to `katello/pulp`? I think it would benefit a *lot* of people. Thanks.

**Comment by ekohl** [comment]
You're absolutely right. https://github.com/Katello/puppet-pulp/issues/143 raised the same issue and is a general issue in our modules: lack of examples. Currently tt's very much focussed on the Katello use case, but it doesn't have to be. Recently I've been taking an interest but that's been mostly focussed on the quality of the code, not documentation.

The directory listing issue was raised in https://github.com/Katello/puppet-pulp/issues/228.

A short note about your code: I think the ```include ::apache::mod::wsgi``` is redundant. In our next release we will also have a ```pulp::repo::upstream``` class that configures the repository for you but we don't handle the dependency (require).

**Comment by TJM** [comment]
NOTE, you also need "epel" (which I found out on #245 )

**Comment by djjudas21** [comment]
@TJM Yep, thanks, we've got EPEL globally included across our estate. It should probably be included more explicitly, though.

**Comment by ekohl** [comment]
With the new README, is this sufficiently addressed or is there still more we can add?

**Comment by ekohl** [comment]
Closing this, but please re-open this if with hints where we are lacking.
