### ISSUE TITLE
Please make a new Release

### ISSUE THREAD

**Issue by SimonHoenscheid** [Katello/puppet-pulp#257]
Would be nice to have the new features from the master branch available on the forge

**Comment by stbenjam** [comment]
Hey, sure thing, I can take care of it.

@ekohl @ehelms Should I do 5.0, since we dropped puppet 3 support? And anything else you want to get in before we do a release?

**Comment by ekohl** [comment]
@stbenjam yes, it must be a 5.0 release. I'd like to get https://github.com/Katello/puppet-pulp/pull/252 in but we need to fix the puppet-qpid dependency. On the other hand, we need to get that done anyway since currently we require a git version of puppet-qpid.

**Comment by ekohl** [comment]
I think most of it is in now, only https://github.com/Katello/puppet-pulp/pull/242 is left on my wish list.

**Comment by ekohl** [comment]
5.0.0 is tagged and on the forge now.
