### ISSUE TITLE
pulp_rpmbind resource creation 'succeeds' for repos that don't exist.

### ISSUE THREAD

**Issue by alexjfisher** [Katello/puppet-pulp#276]
If you use `pulp_rpmbind` to bind to a non-existent repository, the resource should fail to apply.

The provider uses `pulp-consumer`, but the command returns 0 even when it fails.
```
[root@pulp ~]# pulp-consumer rpm bind --repo-id foobar
Repository [foobar] does not exist on the server

[root@pulp ~]# echo $?
0
```
This is with pulp 2.13.2.  Should I try to workaround this in https://github.com/Katello/puppet-pulp/blob/bb68da33dba2e4b4d106ef98aae7b0c9f248f012/lib/puppet/provider/pulp_rpmbind/consumer.rb#L48-L51 ?

**Comment by ekohl** [comment]
That is ugly and I think that's the best place for a workaround. I thought it should be fixed at https://github.com/pulp/pulp/blob/8fab93853ec8bc5b8ff0e4cf8440522488fa4049/client_consumer/pulp/client/consumer/cli.py#L234-L235 but it's actually https://github.com/pulp/pulp/blob/91a1e28c9e7d3dee418d5c7680dbf25c3e7adc63/client_lib/pulp/client/commands/repo/cudl.py#L163 so this looks like a common pattern of not returning an exit code. Makes me wonder what other dragons are lurking around. Maybe this is something to report on https://pulp.plan.io (which was surprisingly hard to find).

**Comment by alexjfisher** [comment]
I've also noticed that the following example is unreliable even when the repo does exist.
```puppet
pulp_rpmbind{ 'nginx-stable':}
package { 'nginx':
  ensure  => installed,
  require => Pulp_rpmbind['nginx-stable']
}
```
Sometimes I get nginx 1.12.x installed (from nginx-stable repo), and sometimes I get 1.10.x from CentOS.
From the [docs](https://docs.pulpproject.org/user-guide/consumer-client/bind.html)
> It may take a few moments for the bind to take effect. It happens asynchronously in the background, and we are working on a way to show positive confirmation of success from pulp-consumer.

I guess any workaround should ideally account for this too.
