### ISSUE TITLE
Do not install qpid and mongodb from pulp

### ISSUE THREAD

**Issue by cristifalcas** [Katello/puppet-pulp#36]
Using those classes inside pulp module stops us from using any custom parameters for them. Also they can't be used anywhere else in the catalog (for other modules).

If you agree, I could make a pull request to remove the declaration of qpid and mongodb from pulp.

Or, in order to keep the current functionality, a new class can be used (pulp::extra or something) that can be included in pulp::init based on a parameter that defaults to true.

Currently we can't install pulp using the upstream module because we need to move the mongodb dbpath to another location.

**Comment by stbenjam** [comment]
Removing qpid makes sense, I think it should probably get moved over `puppet-capsule`.  Mongodb is a hard requirement of pulp, although I wonder if we shouldn't also have that in the capsule module, and find a stock mongodb module to set it up.

**Comment by stbenjam** [comment]
On the other hand, I think the pulp module should be able to configure pulp in a usable state by itself, so maybe the mongodb section could be enabled/dislabed?

**Comment by cristi1979** [comment]
Maybe just include mongodb/qpid and let is use the stock parameters?
