### ISSUE TITLE
module dependency conflict with the main katello module

### ISSUE THREAD

**Issue by teluq-pbrideau** [Katello/puppet-pulp#417]
While trying to setup a new katello server, i’ve stumbled on this:

**katello/pulp** depend on katello/qpid (>= 3.0.0 < 7.0.0)
**katello/katello** depend on katello/qpid (>= 8.0.0 < 10.0.0)

It cannot be satisfied to install both katello and pulp at the same time?

**Comment by ehelms** [comment]
What version of Katello are you trying to setup? `katello/pulp` is for Pulp 2 based Katello which is no longer supported.

**Comment by teluq-pbrideau** [comment]
Oh, I’m following this doc https://docs.theforeman.org/3.3/Installing_Server/index-katello.html
There was mention about pulp, and I blindly searched `pulp` on the forge and took the first result. So I guess the module required is pulpcore then?
https://forge.puppet.com/modules/theforeman/pulpcore/

**Comment by ehelms** [comment]
That is correct, though we expect users to use the instructions in the docs including `foreman-installer --scenario katello`, using the Puppet modules is quite an advanced scenario and requires knowledge of all the right knobs to set. We do not recommend it.

**Comment by teluq-pbrideau** [comment]
Well, all my infrastructure is automated with puppet, and like the flexibility I get from it.  I don’t really want to `exec { '/usr/sbin/foreman-installer' :}`. But yeah, I’m diving pretty deep into all I can to learn about all these knobs! I hope to have a clean setup with puppet once I’m done.
Thanks
