### ISSUE TITLE
Module is missing some apache configuration?

### ISSUE THREAD

**Issue by cristifalcas** [Katello/puppet-pulp#43]
Using the stock pulp module, the apache configuration doesn't work.

Removing all apache classes from "pulp::init" makes pulp work, but you need to manually restart the httpd service (since the service doesn't exist in the catalog anymore).

So I was wondering if it was suppose to work? We have the apache module at version 1.2.0

**Comment by ehelms** [comment]
This is possible. To give some background, this module started and has largely been built with a focus on working with respect to the katello-installer project. Over time, we have and would like to, make our modules more stand-alone for the services they are designed to manage. So, if you find instances of this, please do file issues, or as you have done open PRs. We may be a bit delayed in reviewing them but will address them.
