### ISSUE TITLE
adding nodes support

### ISSUE THREAD

**Issue by cristifalcas** [Katello/puppet-pulp#49]
I would like to ask if it would be ok with you to move child node support to the main class? Mostly because it can't be used without pulp server.

**Comment by ehelms** [comment]
How do you mean? You wouldn't deploy a node onto the same box as a pulp server.

**Comment by cristi1979** [comment]
Then I misunderstood the documentation? This is from http://pulp-user-guide.readthedocs.org/en/2.5-release/nodes.html

The Pulp Nodes concept describes the relationship between two Pulp servers for the purpose of sharing content.

**Comment by ehelms** [comment]
Sorry, I often mixup the 'server' with the 'parent' concept with Pulp nodes and the fact that a parent can be a child and a child a parent of another child. We only ever make use of the 1 parent and N children concept. So, feel free to combine common aspects into manifests, I would just ask that you keep the 'child' aspects their own separate, callable, piece.

**Comment by ekohl** [comment]
What's the status of this? It's a rather old issue and I don't know if we by now have this.

**Comment by ehelms** [comment]
I think this can be closed due to Pulp dropping node support.
